<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>Assembly-CSharp</AssemblyName>
    <RootNamespace>GameStubs</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <NoWarn>CS0649;CS0169;CS0414</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="UnityEngine.Modules" Version="2021.3.33" />
  </ItemGroup>
</Project>